### ISSUE TITLE
Package ot-builder v1.0.5 caused "Cannot find module ot-builder" error.

### ISSUE THREAD

**Issue by GulajavaMinistudio** [be5invis/Iosevka#994]
I'm trying building custom Iosevka font with v6.1.3 source. But after run npm install, and run  "npm run build -- contents::iosevka-custom"

---

* Your font version: 6.1.3
* Your font variant: Custom Font
* Your operating system (name and version): MX Linux Debian 19.4
* Your application using Iosevka: VS Code for build

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: Node JS 14.16.1
* Your _otfcc_ version: I dont know since it bundled with Python afdko build.

---

After digging and checking from last build with 6.0.1 source, i found that ot-builder is different version. In Iosevka v6.1.3 , it use ot-builder v1.0.5 . And for Iosevka 6.0.1, it use ot-builder version v1.0.4. I try to npm install ot-buillder with fixed version ~ 1.0.4 , and trying to build again with Iosevka v6.1.3 source,  it run successfully and smoothly now.

Here my updated package JSON for using ot-builder fixed version .
![Screenshot_2021-05-15_12-43-09](https://user-images.githubusercontent.com/11639412/118349514-5a912a80-b57b-11eb-98aa-6e09c0a3a6b7.png)

And don't forget to include package-lock.json in your repo or project, so we that build custom Iosevka not find any dependency error because different package version  from your machine. Here my package-lock.json .
[Gist for package-lock.json v6.1.3](https://gist.github.com/GulajavaMinistudio/f8a681671293b79356890a262047718b)

**Comment by be5invis** [comment]
Upstream fixed this with 1.0.6. Closing.
